# -*- coding: utf-8 -*-

"""
    countriesapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from countriesapi.decorators import lazy_property
from countriesapi.configuration import Configuration
from countriesapi.controllers.countries_controller import CountriesController


class CountriesapiClient(object):

    config = Configuration

    @lazy_property
    def countries(self):
        return CountriesController()


